name: yoyo_chatt
description: "Simple chat application using flutter and firebase."
publish_to: "none"
version: 2.0.0+200

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utilities
  cupertino_icons: ^1.0.2

  flutter_chat_ui: ^1.6.11
  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_types: ^3.6.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_crashlytics: ^4.0.3
  firebase_storage: ^12.1.1
  firebase_analytics: ^11.2.0

  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  intl: ^0.19.0
  iconly: ^1.0.1

  auto_route: ^8.2.0
  onesignal_flutter: ^5.2.2
  native_id: ^0.0.5
  uuid: ^4.4.2
  # jiffy: ^6.3.1
  timeago: ^3.7.0

  file_picker: ^8.0.6
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  mime: ^1.0.5
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3
  cached_network_image: ^3.4.0
  flutter_expandable_fab: ^2.2.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.8
  riverpod_generator: ^2.3.10
  auto_route_generator: ^8.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts: derry.yaml

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/src\/[**/*.g.dart|**/*.gr.dart|**/*.freezed.dart]
