// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4fejCTMRk202sIa5L5VcRbMHt881zyY',
    appId: '1:1023688435377:android:a68f6469e638d9f10c2490',
    messagingSenderId: '1023688435377',
    projectId: 'flutter-yoyo-chatt',
    storageBucket: 'flutter-yoyo-chatt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZCOOzqvFO6PQxivg439gpRzq8U-sXaA',
    appId: '1:1023688435377:ios:159db1f6bad0c1ef0c2490',
    messagingSenderId: '1023688435377',
    projectId: 'flutter-yoyo-chatt',
    storageBucket: 'flutter-yoyo-chatt.appspot.com',
    androidClientId:
        '1023688435377-beaa381e1kfc3a6fre488fsp0tsvml7k.apps.googleusercontent.com',
    iosClientId:
        '1023688435377-5cciud1nibchq0tcirho4etl1ef5jnfd.apps.googleusercontent.com',
    iosBundleId: 'com.norm.yoyoChatt',
  );
}
